In [1]:
import pandas as pd

In [5]:
cleveland_df = pd.read_csv("clevelandmoa.csv", sep=",", header=0)
chicago_df = pd.read_csv("aic.csv", sep=",", header=0)

In [37]:
carnegie_df = pd.read_csv("cmoa.csv", sep="|", header=0)

In [38]:
carnegie_df['museum'] = 'Carnegie Museum of Art'

In [14]:
top_df = pd.read_csv("101.csv", sep=",", header=0)

In [24]:
carnegie_df.loc[carnegie_df['full_name'] == 'Vincent van Gogh', :]['full_name'] = 'Vincent Van Gogh'

C:\Users\mrindfleisch\AppData\Local\Temp\ipykernel_25908\1624068040.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  carnegie_df.loc[carnegie_df['full_name'] == 'Vincent van Gogh', :]['full_name'] = 'Vincent Van Gogh'

In [44]:
carnegie_df.loc[carnegie_df['full_name'] == 'Sir Peter Paul Rubens', :]

,last_name,cited_name,classification,title,full_name,creation_date,nationality,index,museum
6214,Rubens,"Rubens, Peter P.",paintings,Christ Giving the Keys to St. Peter,Sir Peter Paul Rubens,c. 1700,Flemish,11404,Carnegie Museum of Art
6242,Rubens,"Rubens, Peter P.",paintings,Philip IV of Spain,Sir Peter Paul Rubens,c. 17th century,Flemish,11438,Carnegie Museum of Art
6243,Rubens,"Rubens, Peter P.",paintings,Portrait of El Conde - Duque de Olivares,Sir Peter Paul Rubens,1629,Flemish,11439,Carnegie Museum of Art
6431,Rubens,"Rubens, Peter P.",prints,Saint Catherine in the Clouds,Sir Peter Paul Rubens,early 1620s,Flemish,11671,Carnegie Museum of Art
7447,Rubens,"Rubens, Peter P.",paintings,Head of a Man,Sir Peter Paul Rubens,early 17th century,Flemish,13844,Carnegie Museum of Art

In [41]:
# initial sorting by last name created false entries with multiple entires with same last name,
# switch sorting to full name, then need to conform full name to as listed in top 101.csv -- 
carnegie_df.loc[carnegie_df['full_name'] == 'Vincent van Gogh', ['full_name']] = 'Vincent Van Gogh'
carnegie_df.loc[carnegie_df['full_name'] == 'Edouard Manet', ['full_name']] = 'Édouard Manet'
carnegie_df.loc[carnegie_df['full_name'] == 'Adolphe-William Bouguereau', ['full_name']] = 'William-Adolphe Bouguereau'
carnegie_df.loc[carnegie_df['full_name'] == 'Willem de Kooning', ['full_name']] = 'Willem De Kooning'
carnegie_df.loc[carnegie_df['full_name'] == 'Vassily Kandinsky', ['full_name']] = 'Wassily Kandinsky'
carnegie_df.loc[carnegie_df['full_name'] == 'Théodore  Géricault', ['full_name']] = 'Théodore Géricault'
carnegie_df.loc[carnegie_df['full_name'] == 'Peter Paul Rubens', ['full_name']] = 'Sir Peter Paul Rubens'
carnegie_df.loc[carnegie_df['full_name'] == 'Rembrandt Harmensz. van Rijn', ['full_name']] = 'Rembrandt Van Rijn'
carnegie_df.loc[carnegie_df['full_name'] == 'Joseph Mallord William Turner', ['full_name']] = 'Joseph-Mallord William Turner'
carnegie_df.loc[carnegie_df['full_name'] == 'Jean François Millet', ['full_name']] = 'Jean.François Millet'
carnegie_df.loc[carnegie_df['full_name'] == 'Jean-Baptiste-Camille Corot', ['full_name']] = 'Jean-Baptiste Camille Corot'
carnegie_df.loc[carnegie_df['full_name'] == 'Jean Auguste Dominique Ingres', ['full_name']] = 'Jean-Auguste-Dominique Ingres'
carnegie_df.loc[carnegie_df['full_name'] == 'James Abbott McNeill Whistler', ['full_name']] = 'James Abbot Mcneill Whistler'
carnegie_df.loc[carnegie_df['full_name'] == 'Jean-Desiré-Gustave Courbet', ['full_name']] = 'Gustave Courbet'
carnegie_df.loc[carnegie_df['full_name'] == 'Berthe Morisot', ['full_name']] = 'Berthe Marie Pauline Morisot'

In [62]:
carnegie_df = carnegie_df.rename(columns= {'full_name' : 'artist', 'classification' : 'artwork_genre'  })

In [54]:
cleveland_df['museum'] = 'Cleveland Museum of Art'
cleveland_df = cleveland_df.rename(columns= {'full_name' : 'artist', 'classification' : 'artwork_genre' })

In [87]:

cleveland_df = cleveland_df.fillna(' ')

In [56]:
chicago_df = chicago_df.rename(columns= {'title_of_art' : 'title' })

In [57]:
chicago_df

,artist,title,museum,artwork_genre,creation_date
0,Rembrandt van Rijn,Three Oriental Figures (Jacob and Laban?),Art_Institute_of_Chicago,Prints and Drawings,1641
1,Rembrandt van Rijn,"The Artist's Mother Seated at a Table, Looking...",Art_Institute_of_Chicago,Prints and Drawings,c. 1631
2,Rembrandt van Rijn,The First Oriental Head,Art_Institute_of_Chicago,Prints and Drawings,1635
3,Rembrandt van Rijn,Kostverloren Castle in Decay,Art_Institute_of_Chicago,Prints and Drawings,c. 1652
4,Rembrandt van Rijn,Self-Portrait in a Flat Cap and Embroidered Dress,Art_Institute_of_Chicago,Prints and Drawings,c. 1642
...,...,...,...,...,...
3950,Frans Hals,Portrait of a Lady,Art_Institute_of_Chicago,Painting and Sculpture of Europe,1627
3951,Giotto di Bondone,Prayer for the Flowering of the Rods,Art_Institute_of_Chicago,Prints and Drawings,n.d.
3952,Giotto di Bondone,Ascension of Christ,Art_Institute_of_Chicago,Prints and Drawings,n.d.
3953,Giotto di Bondone,Wedding Procession of Mary and Joseph,Art_Institute_of_Chicago,Prints and Drawings,n.d.
3954,Fra Angelico,Saint Anthony Abbot,Art_Institute_of_Chicago,Painting and Sculpture of Europe,1440/41

In [63]:
carnegie_df

,last_name,cited_name,artwork_genre,title,artist,creation_date,nationality,index,museum
0,Baer,"Baer, Jo",paintings,Untitled,Jo Baer,1964-1965,American,1,Carnegie Museum of Art
1,Ackermann,"Ackermann, Franz",drawings and watercolors,Trans East West (Tew) No. 5: The Attack of the...,Franz Ackermann,1999,German,2,Carnegie Museum of Art
2,Ackermann,"Ackermann, Franz",drawings and watercolors,Trans East West (Tew) No. 6: Rebuilding Beyrut,Franz Ackermann,1999,German,3,Carnegie Museum of Art
3,Ackermann,"Ackermann, Franz",drawings and watercolors,Trans East West (Tew) No. 7: Bombing the Power...,Franz Ackermann,1999,German,4,Carnegie Museum of Art
4,Ackermann,"Ackermann, Franz",drawings and watercolors,Trans East West (Tew) No. 8: Suddenly It was C...,Franz Ackermann,1999,German,5,Carnegie Museum of Art
...,...,...,...,...,...,...,...,...,...
16407,Bastien-Lepage,"Bastien-Lepage, Jules",paintings,A Peasant,Jules Bastien-Lepage,c. 1880,French,28246,Carnegie Museum of Art
16408,Dagnan-Bouveret,"Dagnan-Bouveret, Pascal A.",paintings,Christ and the Disciples at Emmaus,Pascal Adolphe Jean Dagnan-Bouveret,1896-1897,French,28247,Carnegie Museum of Art
16409,Healy,"Healy, George P.",paintings,Portrait of the Artist,George Peter Alexander Healy,c. 1867-1869,American,28248,Carnegie Museum of Art
16410,Sisley,"Sisley, Alfred",paintings,View of Saint-Mammès,Alfred Sisley,c. 1881,French,28249,Carnegie Museum of Art
16411,Inness,"Inness, George",paintings,The Clouded Sun,George Inness,1891,American,28250,Carnegie Museum of Art

In [94]:
cleveland_df.to_csv("cleveland.csv", sep='|', index=False)

In [98]:
type(cleveland_df.iloc[0, 4])

str

In [60]:
cleveland_df.to_csv("cleveland.csv", sep='|', index=False)
chicago_df.to_csv("chicago.csv", sep='|', index=False)
carnegie_df.to_csv("carnegie.csv", sep='|', index=False)

In [67]:
# Read the data from sql View into a Pandas DataFrame
carnegie_filtered_df = pd.read_excel('carnegie_filtered.xlsx')
carnegie_filtered_df

,artist,title,museum,artwork_genre,creation_date,colloq_name
0,Wassily Kandinsky,Radierung für 24 Essais de Jakovski,Carnegie Museum of Art,prints,1934,Kandinsky
1,Joan Miró,Les Trois Soeurs (The Three Sisters),Carnegie Museum of Art,drawings and watercolors,1938,Miró
2,Henri Matisse,Small Black Woodcut (Petit bois noir),Carnegie Museum of Art,prints,1906,Matisse
3,Gerhard Richter,20. Jan. 1990,Carnegie Museum of Art,drawings and watercolors,1990,Richter
4,Willem De Kooning,Untitled Woman,Carnegie Museum of Art,drawings and watercolors,1951,De Kooning
...,...,...,...,...,...,...
757,Waddy Butler Wood,Office Building for the Otis Elevator Company;...,Carnegie Museum of Art,drawings and watercolors,1921,Wood
758,Waddy Butler Wood,"Town House, R Street, Washington, DC; [exterio...",Carnegie Museum of Art,drawings and watercolors,1900,Wood
759,Waddy Butler Wood,Office Buildings; [exterior elevation],Carnegie Museum of Art,drawings and watercolors,1937,Wood
760,Winslow Homer,The Wreck,Carnegie Museum of Art,paintings,1896,Homer
761,James Abbot Mcneill Whistler,Arrangement in Black: Portrait of Señor Pablo ...,Carnegie Museum of Art,paintings,1884,Whistler

In [68]:
carnegie_filtered_df.tail(10)

,artist,title,museum,artwork_genre,creation_date,colloq_name
752,Edward Hopper,Rocky Pedestal,Carnegie Museum of Art,drawings and watercolors,1927,Hopper
753,Edward Hopper,"Tree, Maine",Carnegie Museum of Art,drawings and watercolors,1925-1930,Hopper
754,James Abbot Mcneill Whistler,"The Red House, Paimpol",Carnegie Museum of Art,prints,1893,Whistler
755,Rembrandt Van Rijn,Old Man with a Divided Fur Cap,Carnegie Museum of Art,prints,1640,Rembrandt
756,Waddy Butler Wood,"Country Club; Chevy Chase Club, Chevy Chase, M...",Carnegie Museum of Art,drawings and watercolors,1925,Wood
757,Waddy Butler Wood,Office Building for the Otis Elevator Company;...,Carnegie Museum of Art,drawings and watercolors,1921,Wood
758,Waddy Butler Wood,"Town House, R Street, Washington, DC; [exterio...",Carnegie Museum of Art,drawings and watercolors,1900,Wood
759,Waddy Butler Wood,Office Buildings; [exterior elevation],Carnegie Museum of Art,drawings and watercolors,1937,Wood
760,Winslow Homer,The Wreck,Carnegie Museum of Art,paintings,1896,Homer
761,James Abbot Mcneill Whistler,Arrangement in Black: Portrait of Señor Pablo ...,Carnegie Museum of Art,paintings,1884,Whistler

In [70]:
carnegie_filtered_df = carnegie_filtered_df.drop(columns=['colloq_name'])

In [74]:
cleveland_df= cleveland_df[['artist','title','museum','artwork_genre','creation_date']]

In [93]:
cleveland_df = cleveland_df.fillna('_')
chicago_df = chicago_df.fillna('-')

In [99]:
cleveland_df

,artist,title,museum,artwork_genre,creation_date
0,Eugène Delacroix,Two Boats at the Harbor of Dieppe,Cleveland Museum of Art,Drawing,1854
1,Eugène Delacroix,Greek Cavalry Men Resting in Forest,Cleveland Museum of Art,Painting,1858
2,Eugène Delacroix,A Trapped Tiger,Cleveland Museum of Art,Print,1854
3,Eugène Delacroix,The Blacksmith,Cleveland Museum of Art,Print,1833
4,Eugène Delacroix,Illustrations for Faust,Cleveland Museum of Art,Print,1828
...,...,...,...,...,...
1535,Marcel Duchamp,Contrepèterie,Cleveland Museum of Art,Mixed Media,1968
1536,Caspar David Friedrich,The Woman with the Spider Web between Bare Trees,Cleveland Museum of Art,Print,1803
1537,Caspar David Friedrich,Footbridge with Cross before Trees at a River,Cleveland Museum of Art,Print,c.1803
1538,Gerhard Richter,Elizabeth II,Cleveland Museum of Art,Print,1966
1539,William-Adolphe Bouguereau,Reclining Female Nude,Cleveland Museum of Art,Drawing,

In [79]:
carn_chi_df = pd.merge(
    carnegie_filtered_df, chicago_df,
    on = ["artist", "artist"],
    how = 'left'
)

In [81]:
carn_chi_df = pd.concat([carnegie_filtered_df, chicago_df], ignore_index=True)

In [83]:
allMuseums_df = pd.concat([carn_chi_df, cleveland_df], ignore_index=True)

In [84]:
allMuseums_df

,artist,title,museum,artwork_genre,creation_date
0,Wassily Kandinsky,Radierung für 24 Essais de Jakovski,Carnegie Museum of Art,prints,1934
1,Joan Miró,Les Trois Soeurs (The Three Sisters),Carnegie Museum of Art,drawings and watercolors,1938
2,Henri Matisse,Small Black Woodcut (Petit bois noir),Carnegie Museum of Art,prints,1906
3,Gerhard Richter,20. Jan. 1990,Carnegie Museum of Art,drawings and watercolors,1990
4,Willem De Kooning,Untitled Woman,Carnegie Museum of Art,drawings and watercolors,1951
...,...,...,...,...,...
6252,Marcel Duchamp,Contrepèterie,Cleveland Museum of Art,Mixed Media,1968
6253,Caspar David Friedrich,The Woman with the Spider Web between Bare Trees,Cleveland Museum of Art,Print,1803
6254,Caspar David Friedrich,Footbridge with Cross before Trees at a River,Cleveland Museum of Art,Print,c.1803
6255,Gerhard Richter,Elizabeth II,Cleveland Museum of Art,Print,1966
6256,William-Adolphe Bouguereau,Reclining Female Nude,Cleveland Museum of Art,Drawing,NaN

In [86]:
allMuseums_df.sort_values(
["artist", "title"], ascending=True)

,artist,title,museum,artwork_genre,creation_date
635,Albrecht Dürer,Adam and Eve,Carnegie Museum of Art,prints,1504
1173,Albrecht Dürer,Adam and Eve,Art_Institute_of_Chicago,Prints and Drawings,1504
4957,Albrecht Dürer,Adam and Eve,Cleveland Museum of Art,Print,1504
4992,Albrecht Dürer,Adam and Eve,Cleveland Museum of Art,Print,1504
1082,Albrecht Dürer,Agony in the Garden,Art_Institute_of_Chicago,Prints and Drawings,1515
...,...,...,...,...,...
2716,Édouard Manet,"Under the Lamp (""Once upon a midnight dreary.....",Art_Institute_of_Chicago,Prints and Drawings,1875
621,Édouard Manet,Venice,Carnegie Museum of Art,drawings and watercolors,1878
2668,Édouard Manet,"Victorine Meurent in the Costume of an ""Espada""",Art_Institute_of_Chicago,Prints and Drawings,1862
2618,Édouard Manet,Woman Reading,Art_Institute_of_Chicago,Painting and Sculpture of Europe,1880/81
2694,Édouard Manet,Young Man Standing (Léon Leenhoff) (recto); Sk...,Art_Institute_of_Chicago,Prints and Drawings,1864/65